### ISSUE TITLE
error when pushing to heroku: line 73: [: too many arguments

### ISSUE THREAD

**Issue by mgiraldo** [cyberdelia/heroku-geo-buildpack#20]
This is the first part of the trace when pushing:
```
-----> Fetching custom git buildpack... done
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/cyberdelia/heroku-geo-buildpack.git
=====> Detected Framework: geos/gdal/proj
       Using geos version: <?xml version="1.0" encoding="UTF-8"?>
       Using gdal version: 1.11.0
       Using proj version: 4.8.0
/tmp/buildpackOEjor/bin/compile: line 73: [: too many arguments
-----> Vendoring geo libraries done
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby.git
=====> Detected Framework: Ruby
-----> Compiling Ruby/Rails
...
```

**Comment by mgiraldo** [comment]
a build that used to work is not working anymore

i did upgrade to Ruby 2.2.4

any idea?

i did the `purge_cache` and pushed and get:

```
irb(main):001:0> require 'rgeo'
=> false
irb(main):002:0> RGeo::CoordSys::Proj4.supported?
=> true
irb(main):003:0> RGeo::Geos.supported?
=> false
```

**Comment by mgiraldo** [comment]
this is my buildpacks file: https://github.com/nypl-spacetime/building-inspector/blob/master/.buildpacks

and my `BUILDPACK_URL`: https://github.com/heroku/heroku-buildpack-multi.git

**Comment by mgiraldo** [comment]
upped the `buildpack-ruby` to `v145` and still no luck :pensive:

**Comment by mgiraldo** [comment]
this worked: https://github.com/rgeo/rgeo/issues/125#issuecomment-189192788

but it feels like a hack... is there a more “official” way of doing it?

**Comment by kunalbhatt** [comment]
@mgiraldo did you end up ever working around this hack?

**Comment by mgiraldo** [comment]
i am now using the [multi buildpack functionality native to heroku](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app) and using these buildpacks:

1. https://github.com/peterkeen/heroku-buildpack-vendorbinaries.git
2. https://github.com/diowa/heroku-buildpack-rgeo-prep.git
3. heroku/ruby
