### ISSUE TITLE
.bundle/config grows without bounds, causes dyno processes to fail

### ISSUE THREAD

**Issue by bcm** [cyberdelia/heroku-geo-buildpack#24]
deployed my app to Heroku today and suddenly all of my web, worker and clock processes were dying with R14 errors (memory quota exceeded). they were stuck in endless loops of booting and then being killed by the platform. Heroku support had this to say:

> I see there is a .bundle/config that has grown to 33MB. I've seen this issue before with a combination of a third-party geo buildpack and the Ruby buildpack. The config file grows exponentially between builds, and every time bundler runs it consumes a huge amount of memory just trying to parse it's own config file.

the workaround was to purge the slug cache.

they suggested following up here. I haven't done any investigation of the buildpack to identify if the problem truly is here or where it might lie.

my .buildpacks:

```
https://github.com/cyberdelia/heroku-geo-buildpack.git#1.3
https://github.com/heroku/heroku-buildpack-ruby.git#v129
```

**Comment by cyberdelia** [comment]
It's an issue in bundler, see: https://github.com/bundler/bundler/issues/3261

**Comment by bcm** [comment]
thanks for the reference!
